### PR TITLE
Feat landing testimonial carrousel

### PR DESCRIPTION
**Pull request by aurelien-brabant**
Turn the testimonial section into a carrousel

### CODE REVIEW

**Comment by n1c01a5** [comment]
@aurelien-brabant  I leave a comment about this on Figma. See https://www.figma.com/file/MoGRcnbJjEQntDSQh2La7j?node-id=422:12#155488922

**Comment by aurelien-brabant** [comment]
Done. I also made the font more responsive for the testimonial section. Feel free to feedback

**Comment by n1c01a5** [comment]
Same 😅 can you remove yarn.lock ?

**Comment by n1c01a5** [comment]
I did not merge this PR first 😅. I have to fix the conflict. No pb :)

**Pull request merged**
